name: ldc2
version: 1.10.0
summary: D compiler with LLVM backend
description: |
    LDC is a portable compiler for the D programming Language, with
    modern optimization and code generation capabilities.  It uses
    the official DMD compiler frontend to support the latest version
    of D2, and uses the LLVM Core libraries for code generation.

confinement: classic
grade: stable

apps:
  ldc2:
    command: bin/ldc2
    completer: etc/bash_completion.d/ldc2
  ldmd2:
    command: bin/ldmd2
  ldc-build-runtime:
    command: bin/ldc-build-runtime
  ldc-profdata:
    command: bin/ldc-profdata
  ldc-prune-cache:
    command: bin/ldc-prune-cache

parts:
  ldc:
    source: https://github.com/ldc-developers/ldc.git
    source-tag: v1.10.0
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      cmake ../src \
        -DCMAKE_INSTALL_PREFIX= \
        -DD_COMPILER=../../ldc-bootstrap/build/bin/ldmd2 \
        -DD_FLAGS='-w;-flto=thin' \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS_RELEASE='-O3 -DNDEBUG -Wa,-mrelax-relocations=no' \
        -DLIB_SUFFIX="$(getconf LONG_BIT)" \
        -DLLVM_ROOT_DIR=../../llvm/install \
        -DBUILD_LTO_LIBS=ON \
        -DLDC_INSTALL_LTOPLUGIN=ON \
        -DMULTILIB=ON \
        -DCMAKE_VERBOSE_MAKEFILE=1 \
        -GNinja
      ninja -v
      DESTDIR=../install ninja -v install
      ctest --output-on-failure --verbose -E "std\.net\.curl|std\.process|lit-tests"
    stage:
    - -etc/ldc2.conf
    build-packages:
    - gcc-multilib
    - g++-multilib
    - libedit-dev
    - ninja-build
    - zlib1g-dev
    after:
    - ctest-setup
    - ldc-bootstrap
    - llvm
  ldc-config:
    plugin: dump
    source: ldc-config
    organize:
      ldc2.conf: etc/ldc2.conf

  ldc-license:
    plugin: dump
    source: doc
    organize:
      LICENSE: doc/LICENSE

  ldc-bootstrap:
    source: https://github.com/ldc-developers/ldc.git
    source-tag: v0.17.6
    source-type: git
    source-depth: 1
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_ROOT_DIR=../../llvm/install
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - g++
    - libconfig++-dev
    - libedit-dev
    - zlib1g-dev
    stage-packages:
    - libconfig9
    after:
    - llvm

  llvm:
    source: https://github.com/ldc-developers/llvm.git
    source-tag: ldc-v6.0.1-3
    source-type: git
    source-depth: 1
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DCOMPILER_RT_INCLUDE_TESTS=OFF
    - -DLLVM_BINUTILS_INCDIR=/usr/include
    - -DLLVM_TARGETS_TO_BUILD=AArch64;ARM;Mips;MSP430;NVPTX;PowerPC;X86
    - -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=RISCV;WebAssembly
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - binutils-dev
    - g++

  ctest-setup:
    plugin: nil
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - gdb
    - unzip
